src/ui.web/Models/Transactions/AssociateSecurityModel.cs
using System.Collections.Generic;
using data.models.write;

namespace ui.web.Models.Transactions
{
    public class AssociateSecurityModel
    {
        public int TransactionId { get; set; }
        public BrokerageTransaction Transaction { get; set; }
        public IEnumerable<Security> Securities { get; set; }
        public int? SelectedSecurityId { get; set; }
    }
}

src/ui.web/Models/Transactions/AssociateTransactionTypeModel.cs
using System.Collections.Generic;
using data.models.write;

namespace ui.web.Models.Transactions
{
    public class AssociateTransactionTypeModel
    {
        public int TransactionId { get; set; }
        public BrokerageTransaction Transaction { get; set; }
        public IEnumerable<TransactionType> TransactionTypes { get; set; }
        public TransactionMatch SelectedMatch { get; set; }
    }
}

src/ui.web/Controllers/SecuritiesController.cs
using System;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using data.models.contexts;
using data.models.write;

namespace ui.web.Controllers
{
    public class SecuritiesController : Controller
    {
        DataContext context;

        public SecuritiesController(DataContext context)
        {
            this.context = context;
        }

        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult List()
        {
            return View(context.Securities.ToList());
        }

        [HttpPost]
        public ActionResult Create([Bind(Include = "Ticker, Name")]Security security)
        {
            if (!context.Securities.Any(x => x.Ticker == security.Ticker))
            {
                context.Securities.Add(security);
                context.SaveChanges();
            }

            return RedirectToAction("Detail", new { security.Id });
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var security = context.Securities.Find(id);

            if (security == null)
                return new HttpNotFoundResult();

            return View(security);
        }

        [HttpPost]
        public ActionResult Edit([Bind(Include = "Id, Ticker, Name")]Security security)
        {
            context.Securities.AddOrUpdate(security);
            context.SaveChanges();

            return RedirectToAction("Detail", new { Id = security.Id });
        }

        public ActionResult Detail(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var security = context.Securities.Find(id);

            if (security == null)
                return new HttpNotFoundResult();

            return View(security);
        }

        public ActionResult Delete(int? id)
        {
            if (id != null)
            {
                var security = context.Securities.Include(x => x.BrokerageTransactions).SingleOrDefault(x => x.Id == id);

                if (security != null)
                {
                    context.Securities.Remove(security);
                    context.SaveChanges();
                }
            }

            return RedirectToAction("Index");
        }
    }
}

src/ui.web/Controllers/TransactionsController.cs
using System;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using core.commands;
using core.importers;
using data.models.contexts;
using data.models.write;
using ui.web.Models.Transactions;

namespace ui.web.Controllers
{
    public class TransactionsController : Controller
    {
        VanguardTransactionImporter file_importer;
        AssociateSecurityCommand associate_security_command;
        AssociateTransactionTypeCommand associate_transaction_type_command;
        CreateLotsCommand create_lots_command;
        AutoAssignTradesCommand auto_assign_trades_command;
        DataContext context;

        public TransactionsController(VanguardTransactionImporter file_importer,
                                      AssociateSecurityCommand associate_security_command,
                                      AssociateTransactionTypeCommand associate_transaction_type_command,
                                      CreateLotsCommand create_lots_command,
                                      AutoAssignTradesCommand auto_assign_trades_command,
                                      DataContext context)
        {
            this.file_importer = file_importer;
            this.associate_security_command = associate_security_command;
            this.associate_transaction_type_command = associate_transaction_type_command;
            this.create_lots_command = create_lots_command;
            this.auto_assign_trades_command = auto_assign_trades_command;
            this.context = context;
        }

        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            var brokerage_transactions = context.BrokerageTransactions
                                                .Include(x => x.Account)
                                                .Include(x => x.Security)
                                                .ToList();
            return View(brokerage_transactions);
        }

        public ActionResult Import()
        {
            foreach (string file in Request.Files)
            {
                var hpf = Request.Files[file];
                if (hpf.ContentLength == 0)
                    continue;
                var reader = new StreamReader(hpf.InputStream);
                file_importer.Import(reader.ReadToEnd());
            }

            auto_assign_trades_command.Execute();

            return RedirectToAction("Index");
        }

        public ActionResult AssociateSecurity(int? id)
        {
            if(id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var brokerage_transaction = context.BrokerageTransactions.Find(id);

            if (brokerage_transaction == null)
                return new HttpNotFoundResult();

            return View(new AssociateSecurityModel {
                TransactionId = brokerage_transaction.Id,
                Transaction = brokerage_transaction,
                Securities = context.Securities.ToList() });
        }

        [HttpPost]
        public ActionResult AssociateSecurity([Bind(Include = "TransactionId, SelectedSecurityId")] AssociateSecurityModel model)
        {
            if(model.SelectedSecurityId == null)
                return RedirectToAction("Index");

            associate_security_command.Execute(model.TransactionId, model.SelectedSecurityId.Value);

            return RedirectToAction("Index");
        }

        public ActionResult AssociateTransactionType(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var brokerage_transaction = context.BrokerageTransactions.Find(id);
            if (brokerage_transaction == null)
                return new HttpNotFoundResult();

            return View(new AssociateTransactionTypeModel
                        {
                            TransactionId = brokerage_transaction.Id,
                            Transaction = brokerage_transaction,
                            TransactionTypes = Enum.GetValues(typeof(TransactionType)).OfType<TransactionType>().ToList(),
                            SelectedMatch = new TransactionMatch { Description = brokerage_transaction.TransactionDescription }
                        });
        }

        [HttpPost]
        public ActionResult AssociateTransactionType([Bind(Include = "TransactionId, SelectedMatch")] AssociateTransactionTypeModel model)
        {
            associate_transaction_type_command.Execute(model.TransactionId, model.SelectedMatch);

            return RedirectToAction("Index");
        }
    }
}

src/ui.web/Views/Transactions/AssociateSecurity.cshtml
@model ui.web.Models.Transactions.AssociateSecurityModel
@{
    ViewBag.Title = "Associate Security";
}

<h2>What security is this?</h2>

<div>@Html.Partial("Detail", Model.Transaction)</div>

<div>
    @using (Html.BeginForm("AssociateSecurity", "Transactions"))
          {
              @Html.AntiForgeryToken()
              @Html.HiddenFor(model => model.TransactionId)

              <table>
                  <thead>
                      <th>Ticker</th>
                      <th>Name</th>
                  </thead>
                  @foreach (var security in Model.Securities)
                  {
                      <tr>
                          <td>@Html.RadioButtonFor(m => m.SelectedSecurityId, security.Id)</td>
                          <td>@security.Ticker</td>
                          <td>@security.Name</td>
                      </tr>
                  }
              </table>

              <div class="form-group">
                  <div class="col-md-offset-2 col-md-10">
                      <input type="submit" value="Associate" class="btn btn-default" />
                  </div>
              </div>
          }
    <hr />
    <div>
        @Html.ActionLink("Create Security", "Create", "Securities")
    </div>
</div>

src/ui.web/Views/Transactions/AssociateTransactionType.cshtml
@using data.models.write
@model ui.web.Models.Transactions.AssociateTransactionTypeModel
@{
    ViewBag.Title = "Associate Transaction Type";
}

<h2>What transaction type matches the transaction description?</h2>

<div>@Html.Partial("Detail", Model.Transaction)</div>

@using (Html.BeginForm("AssociateTransactionType", "Transactions"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.TransactionId)
    @Html.HiddenFor(model => model.SelectedMatch.Description)

    <h3>Transaction Types</h3>
    <ul>
        @foreach (var transactionType in Model.TransactionTypes)
        {
            <li>@Html.RadioButtonFor(m => m.SelectedMatch.TransactionType, transactionType) @transactionType</li>
        }
    </ul>

    <h3>How does the description match?</h3>
    <div>
        <ul>
            <li>@Html.RadioButtonFor(m => m.SelectedMatch.TransactionMatchType, TransactionMatchType.ExactMatch, new { @checked = true }) Exact match</li>
            <li>
                @Html.RadioButtonFor(m => m.SelectedMatch.TransactionMatchType, TransactionMatchType.ContainsMatch) Contains @Html.TextBoxFor(model => model.SelectedMatch.ContainsMatchString)
            </li>
        </ul>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Associate" class="btn btn-default" />
        </div>
    </div>
}

src/ui.web/Views/Transactions/Detail.cshtml
@model data.models.write.BrokerageTransaction

<h4>Transaction</h4>
<hr />
<dl class="dl-horizontal">
    <dt>@Html.DisplayName("Account Name")</dt>
    <dd>@Html.DisplayFor(x => x.Account.Name)</dd>

    <dt>@Html.DisplayName("Account Number")</dt>
    <dd>@Html.DisplayFor(x => x.Account.Number)</dd>

    <dt>@Html.DisplayName("Trade Date")</dt>
    <dd>@Html.DisplayFor(x => x.TradeDate)</dd>

    <dt>@Html.DisplayName("Transaction Type")</dt>
    <dd>@Html.DisplayFor(x => x.TransactionType)</dd>

    <dt>@Html.DisplayName("Transaction Name")</dt>
    <dd>@Html.DisplayFor(x => x.TransactionDescription)</dd>

    <dt>@Html.DisplayName("Number of Shares")</dt>
    <dd>@Html.DisplayFor(x => x.Shares)</dd>

    <dt>@Html.DisplayName("Share Price")</dt>
    <dd>@Html.DisplayFor(x => x.SharePrice)</dd>

    <dt>@Html.DisplayName("Gross Amount")</dt>
    <dd>@Html.DisplayFor(x => x.GrossAmount)</dd>

    <dt>@Html.DisplayName("Security Name")</dt>
    <dd>@Html.DisplayFor(x => x.SecurityDescription)</dd>
</dl>

src/ui.web/Views/Transactions/List.cshtml
@using data.models.write
@using Microsoft.Ajax.Utilities
@model IEnumerable<data.models.write.BrokerageTransaction>
@{
    ViewBag.Title = "Transaction List";
}

<div>
    <form action="/Transactions/Import" method="post" enctype="multipart/form-data">
        <input type="file" name="file" id="file" />
        <input type="submit" name="submit" value="Submit" />
    </form>
</div>
<div>
    <table>
        <thead>
            <th>Trade Date</th>
            <th>Account</th>
            <th>Security</th>
            <th>Type</th>
            <th>Shares</th>
            <th>Share Price</th>
            <th>Amount</th>
        </thead>
        @foreach (var transaction in Model)
        {
            <tr>
                <td>@transaction.TradeDate</td>
                <td>@transaction.Account.IfNotNull(x => x.Number)</td>
                <td>@if (transaction.Security != null)
                    {
                        @transaction.Security.Ticker
                    }
                    else
                    {
                        @Html.ActionLink("Not Found", "AssociateSecurity", "Transactions", new { id = transaction.Id }, null)
                    }</td>
                <td>@if (transaction.TransactionType != TransactionType.Missing)
                    {
                        @transaction.TransactionType
                    }
                    else
                    {
                        @Html.ActionLink("Not Found", "AssociateTransactionType", "Transactions", new { id = transaction.Id }, null)
                    }</td>
                <td>@transaction.Shares</td>
                <td>@transaction.SharePrice</td>
                <td>@transaction.NetAmount</td>
            </tr>
        }
    </table>
</div>